### PR TITLE
Feature/milestone4:bookstore-cms

### PR DESCRIPTION
**Pull request by DeliceLydia**
### In this 4th milestone of the bookstore app I implemented :

- A new presentational component(CategoryFilter)
- A new redux action(CHANGE_FILTER)
- A filter.js reducer

Thank you!

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @DeliceLydia, great job on this milestone :+1: README is professional :slightly_smiling_face: Right linter files used :1st_place_medal: Filter.js reducer defaults to "All" :+1: Change filter action added :slightly_smiling_face: The CATEGORY FILTER component is rendered in the BookList container :100: 
However, there are a few comments we need to address before proceeding :+1: KIndly check the comments below:
- The main filter functionality is not working as expected. I tried to filter to any of the categories except the "All" but it returned empty. I also tried to add new data with any of the selected categories but it also returned empty. Let us kindly address it
- Also, the data is not getting stored in the Redux Store, because after a page refresh, the data disappears
- Kindly remove the test command since we do not have test at the moment

Once these are addressed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by DeliceLydia** [comment]
Hello @addod19 ,
Thanks for the feedback but am confused because on my side filter is working and i can
add a new data.. elaborate on that may be am missing something.

Thanks.

**Comment by addod19** [comment]
> Hello @addod19,
> Thanks for the feedback but am confused because on my side filter is working and I can
> add a new data.. elaborate on that may be am missing something.
> 
> Thanks.

Thank you for reaching out!!! Kindly keep in mind that as developers, we need to make our project work on our systems and others. Also, this same bug exists in our live link. The default categories listed are not part of the filter category. Also, the saved data disappears when I reload the page. Kindly check it out and address that.

**Comment by DeliceLydia** [comment]
Hello reviewer!

I worked on the feedback but keeping the data in the redux store I did not may be you can help 
how to do it because I read somewhere that when you refresh the page redux store keep the default
state but I might be missing out something any help will be appreciated.

Thank you!

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 
Hello team @DeliceLydia 👋🏾 👋🏾 congratulations on making it this far in this milestone 🥇 

#### Highlights
- You have worked on all changes requested by the previous TSE ✔️ 
- Persisting data was not a requirement in this milestone, but i commend your efforts in communication as well as backing it up with research 💯 ✔️ 

With that, I approve of this project 😄 

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

**Pull request merged**
